### ISSUE TITLE
语法问题求指教!

### ISSUE THREAD

**Issue by hccgk** [HelloYeah/HYTabbarView#3]
if (!_tabbarView) {
        _tabbarView = ({
            
            HYTabbarView * tabbar = [[HYTabbarView alloc]initWithFrame:CGRectMake(0, 64, [UIScreen mainScreen].bounds.size.width, [UIScreen mainScreen].bounds.size.height - 64)];
            
            TestViewController * vc0 = [[TestViewController alloc]init];
            vc0.title = @"推荐";
            [tabbar addSubItemWithViewController:vc0];

            tabbar;
        });
    }

也就是 
-(UIView*)testview{
    if (!_testview) {
        _testview = ({
            UIView *testview = [UIView new];
            testview;
        });
    }
    return _testview;
}

这种写法没太明白,为什么这么写? 和
-(UIView*)testview{
    if (!_testview) {
        _testview = [UIView new];
    }
    return _testview;
}
写法有什么区别?  第一种的结构为什么是什么样的?它的关键词是什么?

**Comment by HelloYeah** [comment]
第一种写法是把testview 赋值给_testview, 当testview 比较复杂的时候,用第一种写法,代码看起来会舒服一点. 相对简单的视图一般都是用第二种写法.也看个人喜好

**Comment by hccgk** [comment]
谢谢赐教!
